services:
  ml-service:
    build: ./ml-service
    image: mrunmayi12/ml-service:latest
    container_name: model
    ports:
      - "5003:5003"

  preprocessing-service:
    build: ./preprocessing-service
    image: mrunmayi12/preprocessing-service:latest
    container_name: preprocessing
    ports:
      - "5002:5002"
    depends_on:
      - ml-service

  packet-capture-service:
    build: ./packet-capture-service
    image: mrunmayi12/capture-service:latest
    container_name: capture
    ports:
      - "5001:5001"
    cap_add:
      - NET_ADMIN
    depends_on:
      - preprocessing-service
  
  frontend-service:
    build: ./frontend-service
    image: mrunmayi12/frontend-service:latest
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - ml-service

  simulator-service:
    build: ./simulator
    image: mrunmayi12/simulator-service:latest
    container_name: simulator
    ports:
      - "5004:5004"
    depends_on:
      - packet-capture-service
