apiVersion: v1
kind: Service
metadata:
  name: packet-capture-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: packet-capture-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
