apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packet-capture-daemonset
  labels:
    app: packet-capture-service
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: packet-capture-service
  template:
    metadata:
      labels:
        app: packet-capture-service
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: packet-capture-service
        image: mrunmayi12/capture-service:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
            add: ["NET_RAW"]
        ports:
        - containerPort: 5001
          protocol: TCP
