apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  
