apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  # You can access it via http://<minikube-ip>:30080
