apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5003"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: ml-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003