apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: preprocessing-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
