apiVersion: v1
kind: Service
metadata:
  name: simulator-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5004"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: simulator-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
